# Generated by Django 5.0.6 on 2024-05-21 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMesaDeServicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='fechaHoraCreacion',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solOficinaAmbiente',
            field=models.ForeignKey(db_comment='Fecha y hora del registro', on_delete=django.db.models.deletion.PROTECT, to='appMesaDeServicio.oficinaambiente'),
        ),
    ]
