# Generated by Django 4.2.13 on 2024-05-29 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appMesaDeServicio', '0002_remove_solicitud_fechahoracreacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='fechaHoraCreacion',
            field=models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
